# Nome do workflow
name: On workflow dispatch

on:
  workflow_dispatch:

jobs:
  cypress-run-ui:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            spec: cypress/e2e/e2e_test/*.cy.js